'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useState } from 'react';
import { useWorkspace, formatDate, formatDateTime } from './store';
import { type Stage, type Task } from './model';
import { Badge, ConfirmDialog, EmptyState, PageHeader, Timeline, handleDialogKey } from './ui';

export function ClientList() {
  const { data } = useWorkspace(); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('');
  const clients = data.clients.filter(client => `${client.name} ${client.email} ${client.phone}`.toLowerCase().includes(query.toLowerCase()) &&
    (!filter || data.projects.filter(project => project.clientId === client.id).some(project => data.accesses.some(access => access.projectId === project.id && !access.revokedAt)) === (filter === 'claimed')));
  return <><PageHeader eyebrow="Relasi" title="Klien" description="Kontak bisnis dan proyek setelah kesepakatan layanan." />
    <div className="ws-surface ws-filters"><input aria-label="Cari klien" placeholder="Cari nama, email kontak, atau WhatsApp" value={query} onChange={event => setQuery(event.target.value)} /><select aria-label="Filter akses" value={filter} onChange={event => setFilter(event.target.value)}><option value="">Semua akses</option><option value="claimed">Ada proyek yang diklaim</option><option value="unclaimed">Belum diklaim</option></select></div>
    {clients.length ? <div className="ws-card-grid">{clients.map(client => { const projects = data.projects.filter(item => item.clientId === client.id); const last = [...projects].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))[0]; const linked = projects.filter(project => data.accesses.some(access => access.projectId === project.id && !access.revokedAt)).length; return <Link className="ws-project-card" href={`/admin/klien/${client.id}`} key={client.id}><div className="ws-card-top"><span className="ws-ref">KLIEN</span><span className="ws-badge">{linked} akses aktif</span></div><h3>{client.name}</h3><p>{client.phone || client.email || 'Kontak belum diisi'}</p><div className="ws-project-card-foot"><span>{projects.length} proyek · {last ? formatDate(last.updatedAt) : 'Belum ada aktivitas'}</span><span>Detail →</span></div></Link>; })}</div> : <EmptyState title="Klien tidak ditemukan" description="Coba kata kunci atau filter lain." />}
  </>;
}

export function ClientDetail() {
  const { id } = useParams<{ id: string }>(); const { data, updateClient } = useWorkspace(); const client = data.clients.find(item => item.id === id);
  const [name, setName] = useState(client?.name || ''); const [email, setEmail] = useState(client?.email || ''); const [phone, setPhone] = useState(client?.phone || ''); const [error, setError] = useState('');
  if (!client) return <EmptyState title="Klien tidak ditemukan" action={<Link href="/admin/klien" className="ws-button ws-button-secondary">Kembali</Link>} />;
  const projects = data.projects.filter(item => item.clientId === client.id);
  return <><Link className="ws-back" href="/admin/klien">← Semua klien</Link><PageHeader eyebrow="Detail klien" title={client.name} description={`${projects.length} proyek · akses ditentukan per proyek oleh akun pengklaim`} />
    <div className="ws-detail-grid"><section className="ws-surface ws-pad"><h2>Informasi kontak</h2><p className="ws-muted">Email kontak ini tidak mengikat akun Google. Akses diatur melalui tautan proyek.</p>
      <form onSubmit={event => { event.preventDefault(); if (!name.trim() || (email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))) return setError('Nama wajib dan email kontak harus valid bila diisi.'); updateClient(client.id, { name: name.trim(), email: email.trim(), phone: phone.trim() }); setError(''); }} className="ws-form-grid">
        <label className="ws-span-2">Nama klien<input required value={name} onChange={event => setName(event.target.value)} /></label><label className="ws-span-2">Email kontak (opsional)<input type="email" value={email} onChange={event => setEmail(event.target.value)} /></label><label className="ws-span-2">Nomor WhatsApp<input value={phone} onChange={event => setPhone(event.target.value)} /></label>{error && <p className="ws-error ws-span-2" role="alert">{error}</p>}<button className="ws-button ws-button-primary">Simpan kontak</button>
      </form></section>
      <section className="ws-surface ws-pad"><h2>Riwayat layanan</h2>{projects.length ? projects.map(project => { const access = data.accesses.find(item => item.projectId === project.id && !item.revokedAt); const account = data.clientAccounts.find(item => item.id === access?.accountId); return <div className="ws-client-project" key={project.id}><Link href={`/admin/proyek/${project.id}`}><strong>{project.title}</strong></Link><Badge status={project.status} /><small>{data.services.find(item => item.id === project.serviceId)?.name} · {account ? `Diklaim ${account.email}` : 'Belum diklaim'} · {formatDate(project.updatedAt)}</small></div>; }) : <EmptyState title="Belum ada proyek" />}</section></div>
  </>;
}

export function TeamPage() {
  const { data, actorId, createTeamMember, setAdminActive } = useWorkspace();
  const [modal, setModal] = useState(false); const [confirm, setConfirm] = useState<{ id: string; active: boolean } | null>(null);
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState('');
  const [error, setError] = useState(''); const [selected, setSelected] = useState('');
  function close() { setModal(false); setPassword(''); setConfirmPassword(''); setError(''); }
  async function submit(event: React.FormEvent) {
    event.preventDefault(); setError('');
    if (!name.trim() || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return setError('Isi nama dan email yang valid.');
    if (password !== confirmPassword) return setError('Konfirmasi kata sandi tidak cocok.');
    try { await createTeamMember(name, email, password); close(); setName(''); setEmail(''); }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'Anggota belum dapat disiapkan.'); }
  }
  return <><PageHeader eyebrow="Kolaborasi" title="Tim" description="Semua administrator memiliki izin yang setara. PIC hanya menunjukkan tanggung jawab proyek." action={<button className="ws-button ws-button-primary" onClick={() => setModal(true)}>+ Tambah Anggota</button>} />
    <div className="ws-card-grid">{data.admins.map(admin => { const count = data.projects.filter(item => item.picId === admin.id).length; const last = data.activities.find(item => item.actorId === admin.id); const pending = admin.active && admin.mustChangePassword; return <div className="ws-project-card" key={admin.id}><div className="ws-card-top"><span className="ws-avatar">{admin.name[0]}</span><span className="ws-badge">{pending ? 'Perlu ganti kata sandi' : admin.active ? 'Aktif' : 'Nonaktif'}</span></div><h3>{admin.name}</h3><p>{admin.email}</p><div className="ws-team-stats"><span>{count} proyek sebagai PIC</span><span>Aktivitas {formatDateTime(last?.at)}</span></div><div className="ws-inline-actions"><button className="ws-button ws-button-secondary" onClick={() => setSelected(selected === admin.id ? '' : admin.id)}>{selected === admin.id ? 'Tutup detail' : 'Lihat detail'}</button><button className="ws-button ws-button-quiet" disabled={admin.id === actorId || (admin.active && data.admins.filter(item => item.active).length <= 1)} onClick={() => setConfirm({ id: admin.id, active: !admin.active })}>{admin.active ? 'Nonaktifkan' : 'Aktifkan'}</button></div>{selected === admin.id && <div className="ws-team-detail"><h4>Proyek yang ditangani</h4>{data.projects.filter(item => item.picId === admin.id).length ? data.projects.filter(item => item.picId === admin.id).map(project => <Link key={project.id} href={`/admin/proyek/${project.id}`}>{project.title} →</Link>) : <small>Belum menangani proyek.</small>}<h4>Aktivitas terbaru</h4>{data.activities.filter(item => item.actorId === admin.id).slice(0, 3).map(item => <small key={item.id}>{item.text} · {formatDate(item.at)}</small>)}</div>}</div>; })}</div>
    {modal && <div className="ws-dialog-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) close(); }}><div className="ws-dialog" role="dialog" aria-modal="true" aria-labelledby="team-create-title" onKeyDown={event => handleDialogKey(event, close)}><button className="ws-dialog-close" aria-label="Tutup dialog" onClick={close}>×</button><h2 id="team-create-title">Tambah Anggota</h2><p>Akun dibuat langsung. Sampaikan kata sandi awal melalui kanal privat; anggota wajib menggantinya saat pertama masuk.</p>
      <form onSubmit={submit}><label>Nama lengkap<input autoFocus value={name} onChange={event => setName(event.target.value)} required /></label><label>Email<input type="email" value={email} onChange={event => setEmail(event.target.value)} required /></label><label>Kata sandi awal<input type="password" autoComplete="new-password" value={password} onChange={event => setPassword(event.target.value)} minLength={12} required /><small>Minimal 12 karakter, huruf besar, huruf kecil, dan angka. Tidak disimpan oleh frontend.</small></label><label>Konfirmasi kata sandi<input type="password" autoComplete="new-password" value={confirmPassword} onChange={event => setConfirmPassword(event.target.value)} required /></label>{error && <p className="ws-error" role="alert">{error}</p>}<div className="ws-dialog-actions"><button type="button" className="ws-button ws-button-quiet" onClick={close}>Batal</button><button className="ws-button ws-button-primary">Buat akun</button></div></form></div></div>}
    {confirm && <ConfirmDialog title={`${confirm.active ? 'Aktifkan' : 'Nonaktifkan'} administrator?`} description="Perubahan status dicatat dalam riwayat aktivitas. Akun sendiri dan admin aktif terakhir terlindungi." danger={!confirm.active} onConfirm={() => { try { setAdminActive(confirm.id, confirm.active); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Perubahan tidak dapat dilakukan.'); } }} onClose={() => setConfirm(null)} />}{error && !modal && <p className="ws-error" role="alert">{error}</p>}
  </>;
}

export function SettingsPage() {
  const { data, updateService, publishService, updateOffering } = useWorkspace();
  const [tab, setTab] = useState('sop'); const [selected, setSelected] = useState('pendaftaran-merek');
  const service = data.services.find(item => item.id === selected); const editableStages=service?.draftStages || service?.stages || []; const [draftOffering, setDraftOffering] = useState(data.priorityOffering); const [message, setMessage] = useState('');
  function updateStage(stageId: string, patch: Partial<Stage>) { if (!service) return; updateService(service.id, { stages: editableStages.map(stage => stage.id === stageId ? { ...stage, ...patch } : stage) }); }
  function renameTask(stageId: string, taskId: string, title: string) { if (!service || !title.trim()) return; updateService(service.id, { stages: editableStages.map(stage => stage.id === stageId ? { ...stage, tasks: stage.tasks.map(task => task.id === taskId ? { ...task, title: title.trim() } : task) } : stage) }); }
  function stageAction(action:'add'|'remove'|'up'|'down',index?:number){
    if(!service)return;
    const stages=[...editableStages];
    if(action==='add'){const title=window.prompt('Nama tahap baru');if(!title?.trim())return;stages.push({id:crypto.randomUUID(),title:title.trim(),clientLabel:title.trim(),description:'',completionCriteria:'Seluruh tugas pada tahap ini selesai.',waitingKind:'internal',clientVisible:true,tasks:[{id:crypto.randomUUID(),title:'Tinjau dan selesaikan tahap',status:'pending',conditional:false}]});}
    else if(index!==undefined){if(action==='remove'){if(stages.length<=1||!window.confirm('Hapus tahap ini dari draf SOP?'))return;stages.splice(index,1);}else{const next=index+(action==='up'?-1:1);if(next<0||next>=stages.length)return;[stages[index],stages[next]]=[stages[next],stages[index]];}}
    updateService(service.id,{stages});
  }
  function taskAction(stageId: string, action: 'add' | 'remove' | 'up' | 'down', taskId?: string) {
    if (!service) return;
    const stages = editableStages.map(stage => {
      if (stage.id !== stageId) return stage;
      let tasks: Task[] = [...stage.tasks];
      if (action === 'add') { const title = window.prompt('Nama tugas baru'); if (!title?.trim()) return stage; tasks.push({ id: crypto.randomUUID(), title: title.trim(), status: 'pending', conditional: false }); }
      else if (taskId) { const index = tasks.findIndex(item => item.id === taskId); if (index < 0) return stage; if (action === 'remove') { if (!window.confirm('Hapus tugas ini dari template untuk proyek baru?')) return stage; tasks = tasks.filter(item => item.id !== taskId); } else { const next = index + (action === 'up' ? -1 : 1); if (next < 0 || next >= tasks.length) return stage; [tasks[index], tasks[next]] = [tasks[next], tasks[index]]; } }
      return { ...stage, tasks };
    }); updateService(service.id, { stages });
  }
  return <><PageHeader eyebrow="Konfigurasi" title="Pengaturan" description="Atur SOP awal untuk proyek baru dan penawaran prioritas." />
    <div className="ws-tabs" role="tablist" aria-label="Kategori pengaturan">{[['sop', 'Layanan & SOP'], ['prioritas', 'Layanan Prioritas'], ['preferensi', 'Preferensi Sistem']].map(([id, label]) => <button key={id} role="tab" aria-selected={tab === id} className={tab === id ? 'is-active' : ''} onClick={() => setTab(id)}>{label}</button>)}</div>
    {tab === 'sop' && <div className="ws-settings-grid"><div className="ws-surface ws-service-list"><h2>Katalog layanan</h2>{data.services.map(item => <button key={item.id} className={selected === item.id ? 'is-selected' : ''} onClick={() => setSelected(item.id)}><span>{item.name}</span><small>v{item.version}</small></button>)}</div>
      {service && <section className="ws-surface ws-pad"><div className="ws-section-title"><div><h2>{service.name}</h2><p className="ws-muted">SOP diterbitkan v{service.version} · {editableStages.length} tahap {service.draftVersion ? `· Draf v${service.draftVersion}` : ''}</p></div></div><p className="ws-info">Template operasional awal tersedia untuk semua layanan dan dapat diedit. Tim legal VERALEX perlu mengonfirmasi langkah yang berlaku pada setiap kasus. Perubahan disimpan sebagai draf. Terbitkan setelah ditinjau tim legal. Proyek yang sudah dibuat tetap memakai salinan SOP sebelumnya.</p>
        <button className="ws-button ws-button-secondary" onClick={() => stageAction('add')}>+ Tambah tahap</button>
        {editableStages.map((stage,stageIndex) => <div className="ws-template-stage" key={`${service.id}-${stage.id}`}><div className="ws-inline-actions"><button type="button" disabled={stageIndex===0} onClick={() => stageAction('up',stageIndex)}>↑ Naik</button><button type="button" disabled={stageIndex===editableStages.length-1} onClick={() => stageAction('down',stageIndex)}>↓ Turun</button><button type="button" disabled={editableStages.length<=1} onClick={() => stageAction('remove',stageIndex)}>Hapus tahap</button></div><label>Nama tahap internal<input defaultValue={stage.title} onBlur={event => { if (event.target.value.trim() && event.target.value !== stage.title) updateStage(stage.id, { title: event.target.value.trim() }); }} /></label><label>Label untuk klien<input defaultValue={stage.clientLabel} onBlur={event => { if (event.target.value.trim() && event.target.value !== stage.clientLabel) updateStage(stage.id, { clientLabel: event.target.value.trim() }); }} /></label><label className="ws-span-2">Deskripsi tahap<input defaultValue={stage.description} onBlur={event => { if (event.target.value !== stage.description) updateStage(stage.id, { description: event.target.value.trim() }); }} /></label><label className="ws-span-2">Kriteria selesai<input defaultValue={stage.completionCriteria} onBlur={event => { if (event.target.value.trim() && event.target.value !== stage.completionCriteria) updateStage(stage.id, { completionCriteria: event.target.value.trim() }); }} /></label><label className="ws-check"><input type="checkbox" checked={stage.clientVisible} onChange={event => updateStage(stage.id, { clientVisible: event.target.checked })} />Tampilkan kepada klien</label><div className="ws-template-tasks">{stage.tasks.map((task, index) => <div key={task.id}><label className="ws-task-title">{index + 1}. <input aria-label={`Nama tugas ${index + 1}`} defaultValue={task.title} onBlur={event => { if (event.target.value.trim() && event.target.value !== task.title) renameTask(stage.id, task.id, event.target.value); }} /></label><div><button aria-label={`Naikkan ${task.title}`} disabled={index === 0} onClick={() => taskAction(stage.id, 'up', task.id)}>↑</button><button aria-label={`Turunkan ${task.title}`} disabled={index === stage.tasks.length - 1} onClick={() => taskAction(stage.id, 'down', task.id)}>↓</button><button aria-label={`Hapus ${task.title}`} onClick={() => taskAction(stage.id, 'remove', task.id)}>×</button></div></div>)}</div><button className="ws-subtle-button" onClick={() => taskAction(stage.id, 'add')}>+ Tambah tugas</button></div>)}<button className="ws-button ws-button-primary" disabled={!service.draftVersion} onClick={() => publishService(service.id)}>Terbitkan draf SOP</button><h3>Pratinjau timeline klien</h3><Timeline stages={editableStages} client /></section>}
    </div>}
    {tab === 'prioritas' && <form className="ws-surface ws-pad ws-settings-form" onSubmit={event => { event.preventDefault(); updateOffering(draftOffering); setMessage('Penawaran prioritas diperbarui.'); }}><h2>Penawaran prioritas</h2><p className="ws-info">Hanya aktivitas internal VERALEX yang dapat diprioritaskan. Pembayaran tetap belum tersedia sampai integrasi resmi disetujui.</p><label className="ws-check"><input type="checkbox" checked={draftOffering.enabled} onChange={event => setDraftOffering({ ...draftOffering, enabled: event.target.checked })} />Aktifkan penawaran</label><label>Nama penawaran<input required value={draftOffering.title} onChange={event => setDraftOffering({ ...draftOffering, title: event.target.value })} /></label><label>Deskripsi<textarea required rows={3} value={draftOffering.description} onChange={event => setDraftOffering({ ...draftOffering, description: event.target.value })} /></label><label>Komitmen penanganan internal<textarea required rows={2} value={draftOffering.commitment} onChange={event => setDraftOffering({ ...draftOffering, commitment: event.target.value })} /></label><label>Batasan<textarea required rows={2} value={draftOffering.limitations} onChange={event => setDraftOffering({ ...draftOffering, limitations: event.target.value })} /></label><label>Syarat dan ketentuan<textarea required rows={2} value={draftOffering.terms} onChange={event => setDraftOffering({ ...draftOffering, terms: event.target.value })} /></label><label>Harga penawaran (Rp)<input type="number" min="0" value={draftOffering.price} onChange={event => setDraftOffering({ ...draftOffering, price: Number(event.target.value) })} /><small>0 berarti harga ditinjau admin.</small></label><fieldset><legend>Layanan yang memenuhi syarat</legend>{data.services.map(item => <label className="ws-check" key={item.id}><input type="checkbox" checked={draftOffering.serviceIds.includes(item.id)} onChange={event => setDraftOffering({ ...draftOffering, serviceIds: event.target.checked ? [...draftOffering.serviceIds, item.id] : draftOffering.serviceIds.filter(id => id !== item.id) })} />{item.name}</label>)}</fieldset><fieldset><legend>Tahap yang memenuhi syarat</legend><p className="ws-span-2 ws-muted">Kosongkan semua untuk mengizinkan setiap tahap layanan yang dipilih.</p>{data.services.filter(item => draftOffering.serviceIds.includes(item.id)).flatMap(item => item.stages.map(stage => ({ id: `${item.id}:${stage.id}`, label: `${item.name} · ${stage.title}` }))).map(item => <label className="ws-check" key={item.id}><input type="checkbox" checked={draftOffering.stageIds.includes(item.id)} onChange={event => setDraftOffering({ ...draftOffering, stageIds: event.target.checked ? [...draftOffering.stageIds, item.id] : draftOffering.stageIds.filter(id => id !== item.id) })} />{item.label}</label>)}</fieldset><button className="ws-button ws-button-primary">Simpan penawaran</button>{message && <p role="status" className="ws-info">{message}</p>}</form>}
    {tab === 'preferensi' && <div className="ws-detail-grid"><section className="ws-surface ws-pad"><h2>Notifikasi</h2><p className="ws-muted">Pusat notifikasi dalam aplikasi tersedia. Pengiriman email dan push belum dikonfigurasi.</p><Link href="/admin/notifikasi" className="ws-button ws-button-secondary">Buka notifikasi</Link></section><section className="ws-surface ws-pad"><h2>Akun & tampilan</h2><p className="ws-muted">Akun administrator memakai Supabase Auth. Anggota baru wajib mengganti kata sandi awal saat login pertama.</p><Link href="/admin/aktivasi" className="ws-button ws-button-secondary">Ganti kata sandi</Link></section></div>}
  </>;
}
