'use client';

import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import type { Lang } from '@/lib/translations';
import { priorityLabels } from './model';

const messages = {
  en: {
    portal:'Client Portal', website:'Back to Website', help:'Need Help?', loginTitle:'Sign in to Client Portal', loginIntro:'Use the Google account associated with your VERALEX project.', loginEyebrow:'VERALEX CLIENT PORTAL', loginHeadline:'Track Your Project with Confidence.', loginCopy:'Access your VERALEX projects, review progress, and stay informed throughout the service process.', benefit1:'Project Progress', benefit1copy:'Follow the progress of your project.', benefit2:'Centralized Updates', benefit2copy:'View project status and workflow updates in one place.', benefit3:'Private Access', benefit3copy:'Your project information is accessible only to authorized accounts.', google:'Continue with Google', connecting:'Connecting…', invitationLead:"Don't have access yet?", invitationCopy:'After your consultation and service agreement, the VERALEX team will provide a secure project invitation link.', accountHint:'Use the Google account associated with your VERALEX project.', footer:'VERALEX CONSULTING. All rights reserved.', legalTerms:'Terms & Conditions', legalPrivacy:'Privacy Policy', authError:'Google sign-in could not be completed. Please try again.', helpText:'For help with project access, contact the VERALEX team.', operationFailed:'This action could not be completed. Please try again.', operationDone:'Your portal has been updated.',
    navProjects:'My Projects', navNotices:'Notifications', signOut:'Sign out', menuOpen:'Open navigation', menuClose:'Close navigation', skip:'Skip navigation', admin:'Administrator', client:'Client', loading:'Loading your workspace…', loadError:'Your portal is temporarily unavailable', retry:'Try again', noticeEyebrow:'Updates', noticeTitle:'Notifications', noticeDesc:'Important information about your projects.', markAll:'Mark all as read', noNotices:'No notifications yet', noticeEmpty:'Project updates will appear here.',
    hello:'Hello', dashboardDesc:'See your service status and next steps in one place.', projects:'Your Projects', services:'services', noProjects:'No projects linked yet', noProjectsCopy:'Once you claim a project invitation with your Google account, the project will appear here.', actions:'Needs your attention', noAction:'No action needed right now', noActionCopy:'The VERALEX team will let you know if they need any information.', recent:'Recent updates', noUpdates:'No updates yet', actionContact:'Contact your project lead for next steps',
    missingProject:'Project unavailable or access not permitted', missingProjectCopy:'Only projects linked to this account can be viewed.', backPortal:'Back to portal', allProjects:'All projects', currentStatus:'Current Status', externalWait:'The process is with the relevant authority. Timing and decisions are determined by that authority.', clientWait:'The VERALEX team is waiting for information from you through the agreed communication channel.', completed:'This service is complete.', cancelled:'This project has been cancelled.', handling:'The VERALEX team is handling this stage.', nextStep:'Next step', contactPic:'Please contact your project lead for next steps.', teamUpdate:'The team will share the next update with you.', lastUpdated:'Last Updated', journey:'Project Journey', person:'Your Project Contact', pic:'Project lead', contact:'Contact VERALEX', question:'Questions about a project stage? Contact the VERALEX team.', projectUpdates:'Project Updates', priority:'VERALEX Priority Handling', prioritized:'What is prioritized', limitations:'Limitations', price:'Price', reviewPrice:'To be confirmed after review', paymentUnavailable:'Payment is not available in this portal.', requestPriority:'Request Priority Handling', cancelRequest:'Cancel request', unavailablePriority:'Priority handling is not available for this project stage.', noUpdatesProject:'No project updates yet', requestTitle:'Request priority handling?', cancelTitle:'Cancel priority request?', requestDesc:'Your request will be reviewed by the team.', cancelDesc:'This pending request will be cancelled and the VERALEX team will receive a status update.', yesRequest:'Yes, request', yesCancel:'Yes, cancel', cancel:'Cancel',
    stageDone:'Completed', stageActive:'In progress', stageNext:'Next stage', stagesComplete:'{done} of {total} stages', progressLabel:'Completed stages', progressNote:'Progress reflects completed tasks, not an authority processing-time estimate.', status:{draft:'Draft',active:'In Progress',waiting_client:'Waiting for You',waiting_external:'With Authority',review:'In Review',completed:'Completed',rejected:'Unsuccessful',cancelled:'Cancelled',archived:'Archived',pending:'Pending',in_progress:'In Progress',blocked:'On Hold',skipped:'Not Applicable',none:'Not Requested',requested:'Under Review',approved:'Approved',payment_unavailable:'Payment Unavailable'},
    inviteChecking:'Checking invitation…', inviteEyebrow:'Project Access', inviteSignIn:'Sign in to open your invitation.', inviteSignInCopy:'Sign in with your Google account. The first eligible account to claim this invitation will receive project access.', inviteUnauthorized:'This account cannot claim the project.', inviteUnauthorizedCopy:'Use the client Google account associated with this invitation. Administrator accounts cannot claim client projects.', otherAccount:'Sign out and use another account', inviteValid:'Your service progress, in one place.', inviteValidCopy:'Claim access only if this invitation was shared by the VERALEX team through an official conversation.', claim:'Claim project access', claiming:'Processing…', inviteStatus:'Invitation status', claimedOwned:'Project connected', claimedOther:'Invitation already used', expired:'Invitation expired', revoked:'Invitation revoked', invalid:'Invitation unavailable', inviteHelp:'Contact the VERALEX team through an official conversation if you need help with access.', openProject:'Open project', contactTeam:'Contact VERALEX', claimOther:'This invitation was claimed by another Google account.', claimExpired:'This invitation has expired.', claimRevoked:'This invitation has been revoked.', claimInvalid:'This invitation is not valid.', claimFailure:'Project access could not be claimed.', inviteCheckError:'The invitation could not be checked.', inviteAuthError:'Google sign-in failed.', linkTimeout:'Sign-in is taking longer than expected. Please try again.'
  },
  id: {
    portal:'Portal Klien', website:'Kembali ke Website', help:'Butuh Bantuan?', loginTitle:'Masuk ke Portal Klien', loginIntro:'Gunakan akun Google yang terhubung dengan proyek VERALEX Anda.', loginEyebrow:'PORTAL KLIEN VERALEX', loginHeadline:'Pantau Proyek Anda dengan Yakin.', loginCopy:'Akses proyek VERALEX, tinjau progres, dan ikuti informasi selama proses layanan.', benefit1:'Progres Proyek', benefit1copy:'Ikuti perkembangan proyek Anda.', benefit2:'Pembaruan Terpusat', benefit2copy:'Lihat status dan pembaruan alur kerja di satu tempat.', benefit3:'Akses Privat', benefit3copy:'Informasi proyek hanya dapat diakses akun yang berwenang.', google:'Lanjutkan dengan Google', connecting:'Menghubungkan…', invitationLead:'Belum memiliki akses?', invitationCopy:'Setelah konsultasi dan kesepakatan layanan, tim VERALEX akan memberikan tautan undangan proyek yang aman.', accountHint:'Gunakan akun Google yang terhubung dengan proyek VERALEX Anda.', footer:'VERALEX CONSULTING. Hak cipta dilindungi.', legalTerms:'Syarat & Ketentuan', legalPrivacy:'Kebijakan Privasi', authError:'Login Google belum berhasil. Silakan coba lagi.', helpText:'Untuk bantuan akses proyek, hubungi tim VERALEX.', operationFailed:'Tindakan belum dapat dilakukan. Silakan coba lagi.', operationDone:'Portal Anda telah diperbarui.',
    navProjects:'Proyek Saya', navNotices:'Notifikasi', signOut:'Keluar', menuOpen:'Buka navigasi', menuClose:'Tutup navigasi', skip:'Lewati navigasi', admin:'Administrator', client:'Klien', loading:'Memuat workspace…', loadError:'Portal Anda sementara tidak tersedia', retry:'Coba lagi', noticeEyebrow:'Pembaruan', noticeTitle:'Notifikasi', noticeDesc:'Informasi penting dari proyek Anda.', markAll:'Tandai semua dibaca', noNotices:'Belum ada notifikasi', noticeEmpty:'Pembaruan proyek akan muncul di sini.',
    hello:'Halo', dashboardDesc:'Lihat status layanan dan langkah berikutnya di satu tempat.', projects:'Proyek Anda', services:'layanan', noProjects:'Belum ada proyek yang terhubung', noProjectsCopy:'Setelah undangan proyek diklaim dengan akun Google, proyek akan muncul di sini.', actions:'Perlu tindakan Anda', noAction:'Tidak ada tindakan saat ini', noActionCopy:'Tim VERALEX akan memberi kabar bila ada informasi yang diperlukan.', recent:'Pembaruan terbaru', noUpdates:'Belum ada pembaruan', actionContact:'Hubungi PIC untuk tindak lanjut',
    missingProject:'Proyek tidak ditemukan atau tidak diizinkan', missingProjectCopy:'Hanya proyek yang terhubung ke akun ini yang dapat dilihat.', backPortal:'Kembali ke portal', allProjects:'Semua proyek', currentStatus:'Status Saat Ini', externalWait:'Proses berada pada instansi terkait. Waktu dan keputusan ditentukan oleh instansi.', clientWait:'Tim VERALEX sedang menunggu informasi dari Anda melalui kanal komunikasi yang disepakati.', completed:'Layanan ini telah selesai.', cancelled:'Proyek ini telah dibatalkan.', handling:'Tim VERALEX sedang menangani tahap ini.', nextStep:'Langkah berikutnya', contactPic:'Silakan hubungi PIC untuk tindak lanjut.', teamUpdate:'Tim akan memberi kabar berikutnya.', lastUpdated:'Terakhir Diperbarui', journey:'Perjalanan Proyek', person:'Kontak Proyek Anda', pic:'PIC proyek', contact:'Hubungi VERALEX', question:'Ada pertanyaan tentang tahapan? Hubungi tim VERALEX.', projectUpdates:'Pembaruan Proyek', priority:'Layanan Prioritas Penanganan VERALEX', prioritized:'Yang diprioritaskan', limitations:'Batasan', price:'Harga', reviewPrice:'Ditentukan setelah tinjauan', paymentUnavailable:'Pembayaran belum tersedia di portal ini.', requestPriority:'Ajukan Layanan Prioritas', cancelRequest:'Batalkan permintaan', unavailablePriority:'Layanan prioritas belum tersedia untuk tahap proyek ini.', noUpdatesProject:'Belum ada pembaruan', requestTitle:'Ajukan layanan prioritas?', cancelTitle:'Batalkan permintaan prioritas?', requestDesc:'Permintaan akan ditinjau oleh tim.', cancelDesc:'Permintaan yang menunggu tinjauan akan dibatalkan dan tim VERALEX akan menerima pembaruan status.', yesRequest:'Ya, ajukan', yesCancel:'Ya, batalkan', cancel:'Batal',
    stageDone:'Selesai', stageActive:'Sedang berjalan', stageNext:'Tahap berikutnya', stagesComplete:'{done} dari {total} tahap', progressLabel:'Tahap selesai', progressNote:'Progres mengikuti tugas yang selesai, bukan perkiraan waktu proses instansi.', status:{draft:'Draf',active:'Sedang Diproses',waiting_client:'Menunggu Anda',waiting_external:'Menunggu Instansi',review:'Perlu Tinjauan',completed:'Selesai',rejected:'Tidak Berhasil',cancelled:'Dibatalkan',archived:'Diarsipkan',pending:'Menunggu',in_progress:'Sedang Dikerjakan',blocked:'Tertunda',skipped:'Tidak Berlaku',none:'Belum Diajukan',requested:'Menunggu Tinjauan',approved:'Disetujui',payment_unavailable:'Pembayaran Belum Tersedia'},
    inviteChecking:'Memeriksa undangan…', inviteEyebrow:'Akses Proyek', inviteSignIn:'Masuk untuk membuka undangan.', inviteSignInCopy:'Masuk dengan akun Google Anda. Akun pertama yang memenuhi syarat dan mengklaim undangan ini akan memperoleh akses proyek.', inviteUnauthorized:'Akun ini tidak dapat mengklaim proyek.', inviteUnauthorizedCopy:'Gunakan akun Google klien yang terhubung dengan undangan ini. Akun administrator tidak dapat mengklaim proyek klien.', otherAccount:'Keluar dan gunakan akun lain', inviteValid:'Pantau perkembangan layanan Anda.', inviteValidCopy:'Klaim akses hanya jika undangan ini diberikan oleh tim VERALEX melalui percakapan resmi.', claim:'Klaim akses proyek', claiming:'Memproses…', inviteStatus:'Status undangan', claimedOwned:'Proyek sudah terhubung', claimedOther:'Undangan sudah digunakan', expired:'Undangan kedaluwarsa', revoked:'Undangan dicabut', invalid:'Undangan tidak tersedia', inviteHelp:'Hubungi tim VERALEX melalui percakapan resmi bila Anda memerlukan bantuan akses.', openProject:'Buka proyek', contactTeam:'Hubungi VERALEX', claimOther:'Undangan ini telah diklaim oleh akun Google lain.', claimExpired:'Undangan ini telah kedaluwarsa.', claimRevoked:'Undangan ini telah dicabut.', claimInvalid:'Undangan ini tidak berlaku.', claimFailure:'Akses proyek belum dapat diklaim.', inviteCheckError:'Undangan belum dapat diperiksa.', inviteAuthError:'Login dengan Google gagal.', linkTimeout:'Login membutuhkan waktu lebih lama. Silakan coba lagi.'
  },
  zh: {
    portal:'客户门户', website:'返回网站', help:'需要帮助？', loginTitle:'登录客户门户', loginIntro:'请使用与您的 VERALEX 项目关联的 Google 账号。', loginEyebrow:'VERALEX 客户门户', loginHeadline:'安心跟进您的项目。', loginCopy:'访问您的 VERALEX 项目、查看进度，并及时了解服务流程。', benefit1:'项目进度', benefit1copy:'跟进项目的办理进度。', benefit2:'集中更新', benefit2copy:'在一个页面查看项目状态和流程更新。', benefit3:'私密访问', benefit3copy:'只有获授权的账号才能查看项目信息。', google:'使用 Google 继续', connecting:'正在连接…', invitationLead:'尚未获得访问权限？', invitationCopy:'完成咨询并确认服务协议后，VERALEX 团队会向您提供安全的项目邀请链接。', accountHint:'请使用与您的 VERALEX 项目关联的 Google 账号。', footer:'VERALEX CONSULTING。保留所有权利。', legalTerms:'条款与条件', legalPrivacy:'隐私政策', authError:'Google 登录未能完成，请重试。', helpText:'如需项目访问帮助，请联系 VERALEX 团队。', operationFailed:'无法完成此操作，请重试。', operationDone:'客户门户已更新。',
    navProjects:'我的项目', navNotices:'通知', signOut:'退出登录', menuOpen:'打开导航', menuClose:'关闭导航', skip:'跳过导航', admin:'管理员', client:'客户', loading:'正在加载工作区…', loadError:'客户门户暂时无法使用', retry:'重试', noticeEyebrow:'更新', noticeTitle:'通知', noticeDesc:'有关您项目的重要信息。', markAll:'全部标为已读', noNotices:'暂无通知', noticeEmpty:'项目更新将在此处显示。',
    hello:'您好', dashboardDesc:'在一个页面查看服务状态和后续步骤。', projects:'您的项目', services:'项服务', noProjects:'暂无关联项目', noProjectsCopy:'使用 Google 账号领取项目邀请后，项目将显示在此处。', actions:'待您处理', noAction:'目前无需您处理', noActionCopy:'如需您提供信息，VERALEX 团队会通知您。', recent:'最近更新', noUpdates:'暂无更新', actionContact:'请联系项目负责人了解后续步骤',
    missingProject:'项目不存在或无权访问', missingProjectCopy:'您只能查看关联到此账号的项目。', backPortal:'返回客户门户', allProjects:'所有项目', currentStatus:'当前状态', externalWait:'项目正在相关主管机构办理。办理时间和决定由该机构确定。', clientWait:'VERALEX 团队正通过约定的沟通渠道等待您提供信息。', completed:'此项服务已完成。', cancelled:'此项目已取消。', handling:'VERALEX 团队正在处理此阶段。', nextStep:'下一步', contactPic:'请联系项目负责人了解后续安排。', teamUpdate:'团队会向您提供下一次更新。', lastUpdated:'最后更新', journey:'项目进度', person:'您的项目联系人', pic:'项目负责人', contact:'联系 VERALEX', question:'对项目阶段有疑问？请联系 VERALEX 团队。', projectUpdates:'项目更新', priority:'VERALEX 优先处理服务', prioritized:'优先处理内容', limitations:'服务范围限制', price:'价格', reviewPrice:'审核后确认', paymentUnavailable:'此门户暂不支持付款。', requestPriority:'申请优先处理', cancelRequest:'取消申请', unavailablePriority:'此项目阶段暂不提供优先处理服务。', noUpdatesProject:'暂无项目更新', requestTitle:'申请优先处理服务？', cancelTitle:'取消优先处理申请？', requestDesc:'团队将审核您的申请。', cancelDesc:'此待审核申请将被取消，VERALEX 团队会收到状态更新。', yesRequest:'确认申请', yesCancel:'确认取消', cancel:'取消',
    stageDone:'已完成', stageActive:'进行中', stageNext:'下一阶段', stagesComplete:'已完成 {done}/{total} 个阶段', progressLabel:'已完成阶段', progressNote:'进度根据已完成任务显示，不代表主管机构的预计处理时间。', status:{draft:'草稿',active:'进行中',waiting_client:'等待您提供信息',waiting_external:'主管机构处理中',review:'审核中',completed:'已完成',rejected:'未成功',cancelled:'已取消',archived:'已归档',pending:'待处理',in_progress:'进行中',blocked:'暂缓',skipped:'不适用',none:'尚未申请',requested:'审核中',approved:'已批准',payment_unavailable:'暂不支持付款'},
    inviteChecking:'正在检查邀请…', inviteEyebrow:'项目访问', inviteSignIn:'登录以打开项目邀请。', inviteSignInCopy:'请使用 Google 账号登录。首个符合条件并领取此邀请的账号将获得项目访问权限。', inviteUnauthorized:'此账号无法领取项目。', inviteUnauthorizedCopy:'请使用与此邀请关联的客户 Google 账号。管理员账号不能领取客户项目。', otherAccount:'退出并使用其他账号', inviteValid:'随时了解您的服务进度。', inviteValidCopy:'请仅在通过 VERALEX 团队正式沟通收到邀请后领取访问权限。', claim:'领取项目访问权限', claiming:'正在处理…', inviteStatus:'邀请状态', claimedOwned:'项目已关联', claimedOther:'邀请已被使用', expired:'邀请已过期', revoked:'邀请已撤销', invalid:'邀请不可用', inviteHelp:'如需访问帮助，请通过正式沟通渠道联系 VERALEX 团队。', openProject:'打开项目', contactTeam:'联系 VERALEX', claimOther:'此邀请已由其他 Google 账号领取。', claimExpired:'此邀请已过期。', claimRevoked:'此邀请已撤销。', claimInvalid:'此邀请无效。', claimFailure:'无法领取项目访问权限。', inviteCheckError:'无法检查此邀请。', inviteAuthError:'Google 登录失败。', linkTimeout:'登录耗时较长，请重试。'
  }
} as const;
const legalIntro:Record<Lang,string>={en:'For information about using the client portal, please review',id:'Untuk informasi penggunaan portal klien, silakan baca',zh:'有关客户门户的使用说明，请阅读'};
const notificationTitles:Record<Lang,Record<string,string>>={
  en:{project_update:'Project update',priority_reviewed:'Priority request status updated',priority_payment:'Priority payment update'},
  id:{project_update:'Pembaruan proyek',priority_reviewed:'Status permintaan prioritas diperbarui',priority_payment:'Pembaruan pembayaran prioritas'},
  zh:{project_update:'项目更新',priority_reviewed:'优先处理申请状态已更新',priority_payment:'优先处理付款更新'},
};
const priorityStateMessage:Record<Lang,string>={en:'Priority request status: {status}',id:'Status permintaan prioritas: {status}',zh:'优先处理申请状态：{status}'};
const priorityPaymentMessages:Record<Lang,{confirmed:string;failed:string}>={en:{confirmed:'Priority payment confirmed',failed:'Priority payment failed'},id:{confirmed:'Pembayaran prioritas terkonfirmasi',failed:'Pembayaran prioritas gagal'},zh:{confirmed:'优先处理付款已确认',failed:'优先处理付款失败'}};

type Copy = typeof messages.en;
type FlatKey = Exclude<keyof Copy, 'status'>;
type LocaleKey=FlatKey|'legalIntro';
type LocaleContext = { lang: Lang; setLanguage:(lang:Lang)=>void; t:(key:LocaleKey)=>string; status:(key:string)=>string; notificationTitle:(eventType:string|undefined,fallback:string)=>string; notificationMessage:(eventType:string|undefined,message:string)=>string };
const Context=createContext<LocaleContext|null>(null);
export function ClientLocaleProvider({children,initialLanguage='en'}:{children:React.ReactNode;initialLanguage?:Lang}) {
  const [lang,setLangState]=useState<Lang>(initialLanguage);
  const setLanguage=(next:Lang)=>{setLangState(next);localStorage.setItem('veralex-portal-lang',next);localStorage.setItem('veralex-lang',next);document.cookie=`veralex-portal-lang=${next}; Path=/; Max-Age=31536000; SameSite=Lax${location.protocol==='https:'?'; Secure':''}`;document.documentElement.lang=next;};
  useEffect(()=>{document.documentElement.lang=lang;},[lang]);
  const value=useMemo<LocaleContext>(()=>({lang,setLanguage,t:(key)=>key==='legalIntro'?legalIntro[lang]:messages[lang][key] as string,status:(key)=>messages[lang].status[key as keyof typeof messages.en.status]||messages.en.status[key as keyof typeof messages.en.status]||key,notificationTitle:(eventType,fallback)=>eventType?notificationTitles[lang][eventType]||fallback:fallback,notificationMessage:(eventType,message)=>{if(eventType==='priority_reviewed'){const match=message.match(/^Permintaan prioritas menjadi (.+)\.$/);const state=match&&Object.entries(priorityLabels).find(([,label])=>label===match[1])?.[0];if(state)return priorityStateMessage[lang].replace('{status}',messages[lang].status[state as keyof typeof messages.en.status]||messages.en.status[state as keyof typeof messages.en.status]);}if(eventType==='priority_payment'){if(message==='Pembayaran prioritas terkonfirmasi')return priorityPaymentMessages[lang].confirmed;if(message==='Pembayaran prioritas gagal')return priorityPaymentMessages[lang].failed;}return message;}}),[lang]);
  return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useClientLocale(){const value=useContext(Context);if(!value)throw new Error('ClientLocaleProvider is missing');return value;}
export function useOptionalClientLocale(){return useContext(Context);}
export function ClientLanguageSelector(){const {lang,setLanguage}=useClientLocale();const label=lang==='zh'?'语言':lang==='id'?'Bahasa':'Language';return <label className="ws-locale-control"><span className="ws-sr-only">{label}</span><select aria-label={label} value={lang} onChange={e=>setLanguage(e.target.value as Lang)}><option value="en">EN</option><option value="id">ID</option><option value="zh">ZH</option></select></label>;}
export function ClientPortalFrame({children}:{children:React.ReactNode}){const {t,lang}=useClientLocale();const prefix=lang==='en'?'':`/${lang}`;return <div className="ws-client-frame"><header className="ws-client-public-header"><Link className="ws-client-brand" href="/portal/login"><Image src="/logo.webp" alt="VERALEX CONSULTING" width={1024} height={724} priority/><span>{t('portal')}</span></Link><div className="ws-client-header-actions"><ClientLanguageSelector/><Link href="/">{t('website')}</Link><a href="https://wa.me/6281219476385" target="_blank" rel="noreferrer">{t('help')}</a></div></header>{children}<footer className="ws-client-footer"><span>© {new Date().getFullYear()} {t('footer')}</span><span><Link href={`${prefix}/terms-and-conditions`}>{t('legalTerms')}</Link><Link href={`${prefix}/privacy-policy`}>{t('legalPrivacy')}</Link></span></footer></div>;}
