'use client';

import Link from 'next/link';
import Image from 'next/image';
import { usePathname, useRouter } from 'next/navigation';
import { useState } from 'react';
import { useWorkspace, formatDate, formatDateTime, currentStage, completedStages } from './store';
import { priorityLabels, statusLabels, type Project, type ProjectStatus, type Stage } from './model';
import { workspaceBrowser } from '@/lib/workspace/browser';

export function WorkspaceShell({ role, children }: { role: 'admin' | 'client'; children: React.ReactNode }) {
  const pathname = usePathname(); const router=useRouter(); const { data, actorId, clientAccountId, toast, clearToast, ready, error, refresh } = useWorkspace();
  const [menuOpen, setMenuOpen] = useState(false);
  const admin = data.admins.find(item => item.id === actorId); const client = data.clientAccounts.find(item => item.id === clientAccountId);
  const nav = role === 'admin' ? [
    ['/admin', 'Dashboard', '◫'], ['/admin/proyek', 'Proyek', '▤'], ['/admin/klien', 'Klien', '♙'], ['/admin/tim', 'Tim', '♧'], ['/admin/pengaturan', 'Pengaturan', '⚙'],
  ] : [['/portal', 'Proyek saya', '▤'], ['/portal/notifikasi', 'Notifikasi', '♧']];
  const owned = new Set(data.accesses.filter(access => access.accountId === clientAccountId && !access.revokedAt).map(access => access.projectId));
  const notifications = data.notifications.filter(item => item.role === role && !item.read && (role === 'admin' || (item.projectId && owned.has(item.projectId)))).length;
  if (!ready) return <div className="workspace ws-loading" role="status">Menyiapkan workspace…</div>;
  if (error) return <div className="workspace ws-auth-simple"><div className="ws-auth-card"><h1>Workspace belum dapat dimuat</h1><p className="ws-error" role="alert">{error}</p><button className="ws-button ws-button-primary" onClick={()=>refresh().catch(()=>{})}>Coba lagi</button></div></div>;
  return <div className={`workspace ws-${role}`}>
    <a className="ws-skip" href="#workspace-content">Lewati navigasi</a>
    <div className="ws-mobile-top"><Link href={role === 'admin' ? '/admin' : '/portal'} className="ws-brand ws-logo-link" aria-label="VERALEX Consulting"><Image src="/logo.webp" alt="VERALEX Consulting" width={1024} height={724} priority /></Link><button className="ws-icon-button" aria-label={menuOpen ? 'Tutup menu' : 'Buka menu'} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>☰</button></div>
    {menuOpen && <button className="ws-scrim" aria-label="Tutup menu" onClick={() => setMenuOpen(false)} />}
    <aside className={`ws-sidebar ${menuOpen ? 'is-open' : ''}`}>
      <Link href={role === 'admin' ? '/admin' : '/portal'} className="ws-brand ws-logo-link" aria-label="VERALEX Consulting" onClick={() => setMenuOpen(false)}><Image src="/logo.webp" alt="VERALEX Consulting" width={1024} height={724} priority /></Link>
      <nav aria-label="Navigasi utama" className="ws-nav">{nav.map(([href, label, icon]) => <Link key={href} href={href} onClick={() => setMenuOpen(false)} aria-current={pathname === href ? 'page' : undefined} className={`ws-nav-link ${pathname === href || (href !== '/admin' && href !== '/portal' && pathname.startsWith(href + '/')) ? 'is-current' : ''}`}><span aria-hidden="true">{icon}</span>{label}</Link>)}</nav>
      <div className="ws-sidebar-bottom"><Link href={role === 'admin' ? '/admin/notifikasi' : '/portal/notifikasi'} className="ws-nav-link" onClick={() => setMenuOpen(false)}><span aria-hidden="true">♧</span>Notifikasi {notifications > 0 && <b className="ws-count">{notifications}</b>}</Link><div className="ws-identity"><span className="ws-avatar">{(role === 'admin' ? admin?.name : client?.name)?.charAt(0) || 'V'}</span><span><strong>{role === 'admin' ? admin?.name : client?.name}</strong><small>{role === 'admin' ? 'Administrator' : 'Klien'}</small></span></div><button className="ws-subtle-link" onClick={async()=>{await workspaceBrowser().auth.signOut();router.replace(role==='admin'?'/admin/login':'/portal/login');router.refresh();}}>Keluar</button></div>
    </aside>
    <div className="ws-main-wrap"><main id="workspace-content" className="ws-main">{children}</main></div>
    {toast && <div className="ws-toast" role="status">{toast}<button onClick={clearToast} aria-label="Tutup pemberitahuan">×</button></div>}
  </div>;
}
export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) { return <header className="ws-page-header"><div>{eyebrow && <p className="ws-eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description && <p className="ws-muted">{description}</p>}</div>{action && <div className="ws-header-action">{action}</div>}</header>; }
export function Badge({ status }: { status: ProjectStatus | string }) { return <span className={`ws-badge ws-badge-${status}`}>{statusLabels[status as ProjectStatus] || priorityLabels[status as keyof typeof priorityLabels] || status}</span>; }
export function EmptyState({ title, description, action }: { title: string; description?: string; action?: React.ReactNode }) { return <div className="ws-empty"><span className="ws-empty-icon" aria-hidden="true">◌</span><h3>{title}</h3>{description && <p>{description}</p>}{action}</div>; }
export function ProjectCard({ project, role = 'admin' }: { project: Project; role?: 'admin' | 'client' }) { const { data } = useWorkspace(); const client = data.clients.find(item => item.id === project.clientId); const service = data.services.find(item => item.id === project.serviceId); const pic = data.admins.find(item => item.id === project.picId); return <Link href={role === 'admin' ? `/admin/proyek/${project.id}` : `/portal/proyek/${project.id}`} className="ws-project-card"><div className="ws-card-top"><span className="ws-ref">{project.reference}</span><Badge status={project.status} /></div><h3>{project.title}</h3><p>{service?.name} · {client?.name}</p><div className="ws-project-card-foot"><span>{role === 'admin' ? `PIC ${pic?.name || '—'}` : currentStage(project.stages)?.clientLabel}</span><span>Detail →</span></div></Link>; }
export function ProjectTable({ projects }: { projects: Project[] }) { const { data } = useWorkspace(); if (!projects.length) return <EmptyState title="Tidak ada proyek yang cocok" description="Ubah kata kunci atau filter untuk melihat proyek lain." />; return <><div className="ws-table-wrap"><table className="ws-table"><thead><tr><th>Proyek</th><th>Klien / layanan</th><th>Status</th><th>PIC</th><th>Diperbarui</th><th><span className="sr-only">Buka</span></th></tr></thead><tbody>{projects.map(project => <tr key={project.id}><td><Link className="ws-table-title" href={`/admin/proyek/${project.id}`}>{project.title}</Link><small>{project.reference}{project.priority !== 'none' ? ' · Prioritas' : ''}</small></td><td>{data.clients.find(item => item.id === project.clientId)?.name}<small>{data.services.find(item => item.id === project.serviceId)?.name}</small></td><td><Badge status={project.status} /></td><td>{data.admins.find(item => item.id === project.picId)?.name}</td><td>{formatDate(project.updatedAt)}</td><td><Link href={`/admin/proyek/${project.id}`} aria-label={`Buka ${project.title}`}>→</Link></td></tr>)}</tbody></table></div><div className="ws-mobile-cards">{projects.map(project => <ProjectCard key={project.id} project={project} />)}</div></>; }
export function Timeline({ stages, client = false }: { stages: Stage[]; client?: boolean }) { const active = currentStage(stages)?.id; return <ol className="ws-timeline">{stages.filter(stage => !client || stage.clientVisible).map((stage, index) => { const complete = stage.tasks.length > 0 && stage.tasks.every(task => task.status === 'completed' || task.status === 'skipped'); return <li key={stage.id} className={complete ? 'is-complete' : active === stage.id ? 'is-active' : ''}><span className="ws-timeline-dot">{complete ? '✓' : index + 1}</span><div><strong>{client ? stage.clientLabel : stage.title}</strong><small>{complete ? 'Selesai' : active === stage.id ? 'Sedang berjalan' : 'Tahap berikutnya'}</small></div></li>; })}</ol>; }
export function ProgressSummary({ project }: { project: Project }) { const count = completedStages(project.stages); return <div className="ws-progress"><div><strong>{count} dari {project.stages.length} tahap</strong><span>{currentStage(project.stages)?.clientLabel}</span></div><div className="ws-progress-track" role="progressbar" aria-valuenow={count} aria-valuemin={0} aria-valuemax={project.stages.length} aria-label="Tahap selesai"><span style={{ width: `${project.stages.length ? count / project.stages.length * 100 : 0}%` }} /></div><small>Progres mengikuti tugas yang selesai, bukan perkiraan waktu proses instansi.</small></div>; }
export function handleDialogKey(event: React.KeyboardEvent<HTMLDivElement>, onClose: () => void) { if (event.key === 'Escape') { onClose(); return; } if (event.key !== 'Tab') return; const focusable = Array.from(event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), select:not(:disabled), textarea:not(:disabled), a[href]')); if (!focusable.length) return; const first = focusable[0]; const last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }
export function ConfirmDialog({ title, description, confirmLabel = 'Ya, lanjutkan', danger = false, onConfirm, onClose }: { title: string; description: string; confirmLabel?: string; danger?: boolean; onConfirm: () => void; onClose: () => void }) { return <div className="ws-dialog-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><div className="ws-dialog" role="dialog" aria-modal="true" aria-labelledby="ws-dialog-title" onKeyDown={event => handleDialogKey(event, onClose)}><button autoFocus className="ws-dialog-close" aria-label="Tutup dialog" onClick={onClose}>×</button><h2 id="ws-dialog-title">{title}</h2><p>{description}</p><div className="ws-dialog-actions"><button className="ws-button ws-button-quiet" onClick={onClose}>Batal</button><button className={`ws-button ${danger ? 'ws-button-danger' : 'ws-button-primary'}`} onClick={() => { onConfirm(); onClose(); }}>{confirmLabel}</button></div></div></div>; }
export function NoticeList({ role }: { role: 'admin' | 'client' }) { const { data, clientAccountId, markRead, markAllRead } = useWorkspace(); const router = useRouter(); const owned = new Set(data.accesses.filter(access => access.accountId === clientAccountId && !access.revokedAt).map(access => access.projectId)); const notices = data.notifications.filter(item => item.role === role && (role === 'admin' || (item.projectId && owned.has(item.projectId)))).sort((a, b) => b.at.localeCompare(a.at)); return <><PageHeader eyebrow="Pembaruan" title="Notifikasi" description="Informasi penting dari proyek Anda." action={<button className="ws-button ws-button-secondary" onClick={() => markAllRead(role)} disabled={!notices.some(item => !item.read)}>Tandai semua dibaca</button>} />{notices.length ? <div className="ws-surface ws-notice-list">{notices.map(notice => <button key={notice.id} className={`ws-notice ${!notice.read ? 'is-unread' : ''}`} onClick={() => { markRead(notice.id); router.push(notice.target); }}><span className="ws-notice-mark" /><span><strong>{notice.title}</strong><span>{notice.message}</span><small>{formatDateTime(notice.at)}</small></span><span aria-hidden="true">↗</span></button>)}</div> : <EmptyState title="Belum ada notifikasi" description="Pembaruan proyek akan muncul di sini." />}</>; }
