export interface ServiceItem {
    slug: string;
    category: string;
    categoryEn: string;
    categoryZh: string;
    title: string;
    titleEn: string;
    titleZh: string;
    description: string;
    descriptionEn: string;
    descriptionZh: string;
    price: string;
    originalPrice?: string;
    discountBadge?: string;
    discountBadgeEn?: string;
    discountBadgeZh?: string;
    features: string[];
    featuresEn: string[];
    featuresZh: string[];
}

export const serviceData: ServiceItem[] = [
    // === Kekayaan Intelektual ===
    {
        slug: 'pendaftaran-merek',
        category: 'Kekayaan Intelektual',
        categoryEn: 'Intellectual Property',
        categoryZh: '知识产权保护',
        title: 'Pendaftaran Merek',
        titleEn: 'Trademark Registration',
        titleZh: '商标注册申请',
        description: 'Jasa pendaftaran merek dagang di Indonesia melalui DJKI Kemenkumham. Kami membantu dari pengecekan hingga sertifikat merek terbit.',
        descriptionEn: 'Trademark registration service in Indonesia through DJKI Ministry of Law. We assist from checking to certificate issuance.',
        descriptionZh: '在印尼知识产权局 (DJKI Kemenkumham) 申请商标注册，全流程代理直至拿到官方证书。',
        price: 'Rp3.000.000',
        originalPrice: 'Rp6.000.000',
        discountBadge: 'DISKON 50%',
        discountBadgeEn: '50% OFF',
        discountBadgeZh: '限时5折',
        features: ['Pengecekan ketersediaan merek', 'Pengajuan ke DJKI', 'Konsultasi kelas merek', 'Monitoring status pendaftaran', 'Pengurusan hingga sertifikat terbit'],
        featuresEn: ['Trademark availability check', 'Submission to DJKI', 'Trademark class consultation', 'Registration status monitoring', 'Processing until certificate issuance'],
        featuresZh: ['商标数据库查重检索', '提交申请至 DJKI', '尼斯商标分类指导', '注册审核全流程监控', '代理直至拿到官方证书'],
    },
    {
        slug: 'perpanjangan-merek',
        category: 'Kekayaan Intelektual',
        categoryEn: 'Intellectual Property',
        categoryZh: '知识产权保护',
        title: 'Perpanjangan Merek',
        titleEn: 'Trademark Renewal',
        titleZh: '商标续展服务',
        description: 'Jasa perpanjangan hak merek yang sudah terdaftar agar tetap terlindungi secara hukum.',
        descriptionEn: 'Trademark renewal service to keep your registered trademark legally protected.',
        descriptionZh: '为已注册的商标办理法定续展，确保您的专属保护权持续有效。',
        price: 'Rp6.000.000',
        features: ['Perpanjangan masa perlindungan merek', 'Pengajuan ke DJKI', 'Konsultasi hukum merek'],
        featuresEn: ['Extension of trademark protection period', 'Submission to DJKI', 'Trademark legal consultation'],
        featuresZh: ['延长商标法定保护期', '官方提交至 DJKI', '商标法律合规咨询'],
    },
    {
        slug: 'pengalihan-merek',
        category: 'Kekayaan Intelektual',
        categoryEn: 'Intellectual Property',
        categoryZh: '知识产权保护',
        title: 'Pengalihan Merek',
        titleEn: 'Trademark Transfer',
        titleZh: '商标所有权转让',
        description: 'Jasa pengalihan hak kepemilikan merek dari satu pihak ke pihak lain secara legal.',
        descriptionEn: 'Legal trademark ownership transfer service from one party to another.',
        descriptionZh: '依法将已注册商标的所有权从一方转让给另一方，出具公证文件。',
        price: 'Rp3.000.000',
        features: ['Proses pengalihan kepemilikan', 'Akta notaris pengalihan', 'Updating data di DJKI'],
        featuresEn: ['Ownership transfer process', 'Transfer notarial deed', 'Data update at DJKI'],
        featuresZh: ['所有权转让全流程办理', '公证处起草转让契约', '在 DJKI 变更登记数据'],
    },
    {
        slug: 'hak-cipta',
        category: 'Kekayaan Intelektual',
        categoryEn: 'Intellectual Property',
        categoryZh: '知识产权保护',
        title: 'Pendaftaran Hak Cipta',
        titleEn: 'Copyright Registration',
        titleZh: '著作权/版权登记',
        description: 'Perlindungan karya cipta Anda secara hukum melalui pendaftaran di Kemenkumham.',
        descriptionEn: 'Legal protection for your creative works through registration at the Ministry of Law.',
        descriptionZh: '向印尼司法与人权部申请作品版权登记，获得法定知识产权保护。',
        price: 'Rp2.500.000',
        features: ['Pendaftaran hak cipta resmi', 'Konsultasi jenis karya cipta', 'Sertifikat hak cipta'],
        featuresEn: ['Official copyright registration', 'Creative work type consultation', 'Copyright certificate'],
        featuresZh: ['官方版权登记办理', '作品类型评估与咨询', '官方版权登记证书'],
    },
    {
        slug: 'desain-industri',
        category: 'Kekayaan Intelektual',
        categoryEn: 'Intellectual Property',
        categoryZh: '知识产权保护',
        title: 'Pendaftaran Desain Industri',
        titleEn: 'Industrial Design Registration',
        titleZh: '工业设计专利登记',
        description: 'Lindungi desain produk Anda dari peniruan dengan pendaftaran desain industri.',
        descriptionEn: 'Protect your product design from imitation through industrial design registration.',
        descriptionZh: '申请产品外观设计及工业外观专利，防止市场仿冒及非法抄袭。',
        price: 'Rp4.500.000',
        features: ['Pendaftaran desain industri', 'Perlindungan hukum desain', 'Konsultasi desain'],
        featuresEn: ['Industrial design registration', 'Design legal protection', 'Design consultation'],
        featuresZh: ['工业设计专利申请', '外观设计法律保护', '外观专利专业咨询'],
    },

    // === Legalitas Perusahaan ===
    {
        slug: 'pt-pmdn',
        category: 'Legalitas Perusahaan',
        categoryEn: 'Company Formation',
        categoryZh: '公司设立与合规',
        title: 'Pendirian PT PMDN / PT Umum',
        titleEn: 'Domestic Company (PT PMDN) Establishment',
        titleZh: '印尼内资公司 (PT PMDN)',
        description: 'Pendirian PT PMDN lengkap dengan legalitas dan izin usaha. Sudah termasuk website company profile GRATIS.',
        descriptionEn: 'Complete PT PMDN establishment with business legality and permits. Includes FREE company profile website.',
        descriptionZh: '设立印尼本土内资公司，含完整公证书及全套合规执照，赠送企业官网设计。',
        price: 'Rp7.000.000',
        features: [
            'Pengecekan dan Pemesanan Nama', 'Akta Pendirian dari Notaris', 'SK/SKT Pengesahan Kemenkumham',
            'NPWP Perusahaan', 'NIB / TDP', 'Sertifikat Standar / SIUP',
            'Free Website Company Profile', 'Free Konsultasi Hukum Bisnis',
        ],
        featuresEn: [
            'Name checking and booking', 'Notarial Deed of Establishment', 'Ministry of Law Approval',
            'Company Tax ID (NPWP)', 'Business Identification Number (NIB)', 'Business License (SIUP)',
            'Free Company Profile Website', 'Free Business Legal Consultation',
        ],
        featuresZh: [
            '公司核名与预订', '公证人起草设立契约', '印尼司法部批文 SK/SKT',
            '公司专属税务证 NPWP', '商业登记号 NIB / TDP', '标准经营许可 / SIUP',
            '免费赠送企业官网设计', '免费商业法律合规咨询',
        ],
    },
    {
        slug: 'pt-pma',
        category: 'Legalitas Perusahaan',
        categoryEn: 'Company Formation',
        categoryZh: '公司设立与合规',
        title: 'Pendirian PT PMA',
        titleEn: 'Foreign Investment Company (PT PMA)',
        titleZh: '外商独资/合资公司 (PT PMA)',
        description: 'Pendirian perusahaan penanaman modal asing (PMA) di Indonesia dengan legalitas lengkap.',
        descriptionEn: 'Foreign investment company establishment in Indonesia with complete legal compliance.',
        descriptionZh: '外国投资者在印尼开办合规企业的法定标准实体结构，全套合规证书。',
        price: 'Rp15.000.000',
        features: ['Akta Pendirian PMA', 'SK Kemenkumham', 'NPWP', 'NIB', 'Izin Investasi', 'Konsultasi BKPM'],
        featuresEn: ['PMA Establishment Deed', 'Ministry Approval', 'Tax ID', 'Business ID', 'Investment Permit', 'BKPM Consultation'],
        featuresZh: ['外资设立公证书', '印尼司法部批文 SK', '企业专属税号 NPWP', '商业登记号 NIB', '投资许可证书', 'BKPM 顾问与 LKPM 账号配置'],
    },
    {
        slug: 'pt-perorangan',
        category: 'Legalitas Perusahaan',
        categoryEn: 'Company Formation',
        categoryZh: '公司设立与合规',
        title: 'Pendirian PT Perorangan',
        titleEn: 'Individual Company (PT) Establishment',
        titleZh: '个人独资公司 (PT Perorangan)',
        description: 'PT dengan pemilik tunggal — solusi legal terjangkau untuk wirausaha.',
        descriptionEn: 'Single-owner PT — affordable legal solution for entrepreneurs.',
        descriptionZh: '单人即可成立的独立法人公司——微型初创企业与自由职业者的经济合规方案。',
        price: 'Rp1.500.000',
        features: ['Akta Pendirian', 'SK Kemenkumham', 'NPWP', 'NIB', 'Sertifikat Standar'],
        featuresEn: ['Establishment Deed', 'Ministry Approval', 'Tax ID', 'Business ID', 'Standard Certificate'],
        featuresZh: ['设立声明文件', '印尼司法部电子批文', '公司专属税号 NPWP', '商业登记号 NIB', '标准经营许可证书'],
    },
    {
        slug: 'pendirian-cv',
        category: 'Legalitas Perusahaan',
        categoryEn: 'Company Formation',
        categoryZh: '公司设立与合规',
        title: 'Pendirian CV',
        titleEn: 'CV (Partnership) Establishment',
        titleZh: 'CV 合伙企业设立',
        description: 'Pendirian CV untuk usaha kecil dan menengah dengan proses cepat dan legalitas lengkap.',
        descriptionEn: 'CV establishment for small and medium businesses with fast processing and complete legality.',
        descriptionZh: '为中小型初创企业设立 CV 合伙公司，办理快捷，合规手续健全。',
        price: 'Rp3.000.000',
        features: ['Akta Pendirian CV', 'SK Kemenkumham', 'NPWP CV', 'NIB', 'Konsultasi hukum'],
        featuresEn: ['CV Establishment Deed', 'Ministry Approval', 'CV Tax ID', 'Business ID Number', 'Legal consultation'],
        featuresZh: ['CV 设立公证书', '印尼司法部批文 SK', 'CV 专属税号 NPWP', '商业登记号 NIB', '商业法律咨询'],
    },

    // === Visa & ITAS ===
    {
        slug: 'itas-investor-1-tahun',
        category: 'Visa & ITAS',
        categoryEn: 'Visa & ITAS',
        categoryZh: '签证与居留许可',
        title: 'ITAS Investor 1 Tahun',
        titleEn: 'Investor ITAS (1 Year)',
        titleZh: '1年期投资者居留许可 (ITAS Investor)',
        description: 'Izin tinggal terbatas untuk investor asing di Indonesia selama 1 tahun.',
        descriptionEn: 'Limited stay permit for foreign investors in Indonesia for 1 year.',
        descriptionZh: '专为在印尼投资的外籍股东办理的1年期官方限期居留许可。',
        price: 'Rp16.000.000',
        features: ['Pengurusan ITAS lengkap', 'Konsultasi persyaratan', 'Pendampingan imigrasi', 'Monitoring status'],
        featuresEn: ['Complete ITAS processing', 'Requirements consultation', 'Immigration assistance', 'Status monitoring'],
        featuresZh: ['全套 ITAS 申办代理', '申请条件与合规咨询', '印尼移民局现场配合', '办结进度实时追踪'],
    },
    {
        slug: 'itas-investor-2-tahun',
        category: 'Visa & ITAS',
        categoryEn: 'Visa & ITAS',
        categoryZh: '签证与居留许可',
        title: 'ITAS Investor 2 Tahun',
        titleEn: 'Investor ITAS (2 Years)',
        titleZh: '2年期投资者居留许可 (ITAS Investor)',
        description: 'Izin tinggal terbatas untuk investor asing di Indonesia selama 2 tahun.',
        descriptionEn: 'Limited stay permit for foreign investors in Indonesia for 2 years.',
        descriptionZh: '专为在印尼投资的外籍股东办理的2年期官方限期居留许可，性价比更高。',
        price: 'Rp18.000.000',
        features: ['Pengurusan ITAS 2 tahun', 'Konsultasi persyaratan', 'Pendampingan imigrasi', 'Monitoring status'],
        featuresEn: ['2-year ITAS processing', 'Requirements consultation', 'Immigration assistance', 'Status monitoring'],
        featuresZh: ['2年期 ITAS 申办代理', '申请条件与合规咨询', '印尼移民局现场配合', '办结进度实时追踪'],
    },
    {
        slug: 'visa-c2',
        category: 'Visa & ITAS',
        categoryEn: 'Visa & ITAS',
        categoryZh: '签证与居留许可',
        title: 'Visa C2',
        titleEn: 'Visa C2 (Social-Cultural)',
        titleZh: 'C2 商务文化签证',
        description: 'Visa kunjungan sosial budaya untuk tinggal sementara di Indonesia.',
        descriptionEn: 'Social-cultural visit visa for temporary stay in Indonesia.',
        descriptionZh: '用于商务考察、学术交流及文化活动的印尼短期入境签证。',
        price: 'Rp3.500.000',
        features: ['Pengurusan visa C2', 'Surat sponsor', 'Konsultasi persyaratan'],
        featuresEn: ['Visa C2 processing', 'Sponsor letter', 'Requirements consultation'],
        featuresZh: ['C2 签证申办代理', '担保邀请函起草', '签证条件合规咨询'],
    },
    {
        slug: 'visa-d2-1-tahun',
        category: 'Visa & ITAS',
        categoryEn: 'Visa & ITAS',
        categoryZh: '签证与居留许可',
        title: 'Visa D2 (1 Tahun)',
        titleEn: 'Visa D2 (1 Year)',
        titleZh: '1年期 D2 多次往返签证',
        description: 'Visa tinggal terbatas untuk berbagai keperluan selama 1 tahun.',
        descriptionEn: 'Limited stay visa for various purposes for 1 year.',
        descriptionZh: '1年有效期的多次入境签证，满足高管频繁出入印尼需求。',
        price: 'Rp6.000.000',
        features: ['Pengurusan Visa D2', 'Dokumen lengkap', 'Pendampingan proses'],
        featuresEn: ['Visa D2 processing', 'Complete documentation', 'Process assistance'],
        featuresZh: ['D2 签证申办代理', '全套证明文件整理', '申办过程全程协助'],
    },
    {
        slug: 'visa-d2-2-tahun',
        category: 'Visa & ITAS',
        categoryEn: 'Visa & ITAS',
        categoryZh: '签证与居留许可',
        title: 'Visa D2 (2 Tahun)',
        titleEn: 'Visa D2 (2 Years)',
        titleZh: '2年期 D2 多次往返签证',
        description: 'Visa tinggal terbatas untuk berbagai keperluan selama 2 tahun.',
        descriptionEn: 'Limited stay visa for various purposes for 2 years.',
        descriptionZh: '2年有效期的多次入境签证，满足中长期商务出行需求。',
        price: 'Rp9.500.000',
        features: ['Pengurusan Visa D2', 'Dokumen lengkap', 'Pendampingan proses'],
        featuresEn: ['Visa D2 processing', 'Complete documentation', 'Process assistance'],
        featuresZh: ['D2 签证申办代理', '全套证明文件整理', '申办过程全程协助'],
    },
    {
        slug: 'kitas-kerja',
        category: 'Visa & ITAS',
        categoryEn: 'Visa & ITAS',
        categoryZh: '签证与居留许可',
        title: 'KITAS Kerja (1 Tahun)',
        titleEn: 'Work KITAS (1 Year)',
        titleZh: '1年期外籍员工工作许可 (KITAS Kerja)',
        description: 'KITAS untuk pekerja asing, sudah termasuk DPKK ($1200 USD) dan RPTKA.',
        descriptionEn: 'Work permit for foreign workers, including DPKK ($1200 USD) and RPTKA.',
        descriptionZh: '专为外籍员工办理的工作许可，已包含 DPKK 发展基金 ($1200美元) 和 RPTKA 用工配额。',
        price: 'Rp45.000.000',
        features: ['KITAS kerja 1 tahun', 'Termasuk DPKK ($1200 USD)', 'Termasuk RPTKA', 'Pendampingan imigrasi'],
        featuresEn: ['1-year work KITAS', 'Includes DPKK ($1200 USD)', 'Includes RPTKA', 'Immigration assistance'],
        featuresZh: ['1年期工作 KITAS', '已含 DPKK 基金 ($1200美元)', '已含 RPTKA 劳工配额', '移民局及劳工部全程协调'],
    },
];

export function getServiceBySlug(slug: string): ServiceItem | undefined {
    return serviceData.find((s) => s.slug === slug);
}

export function getAllSlugs(): string[] {
    return serviceData.map((s) => s.slug);
}
