import type { Lang } from '@/lib/translations';
import type { LegalDocument } from './privacy';

const en: LegalDocument = {
  title: 'Terms & Conditions',
  description: 'Terms for using the VERALEX CONSULTING website and client project tracking portal.',
  intro: 'These terms explain use of the VERALEX website and client portal. A quotation or individually agreed service contract sets the specific scope, price, and deliverables for an engagement.',
  sections: [
    {id:'scope',title:'Scope and agreement',paragraphs:['These terms concern the public website, accounts, project tracking portal, and related digital features offered under the VERALEX CONSULTING name. They do not silently replace a separately agreed written quotation or service agreement. If an individual agreement addresses a specific service matter differently, that agreement governs that matter to the extent permitted by law.']},
    {id:'definitions',title:'Definitions',paragraphs:['“VERALEX” means the operator of the VERALEX CONSULTING website and services. A “User” visits or uses the site; a “Client” engages with a service or receives project access; an “Administrator” is an authorized VERALEX team member. “Services” are the consulting and administrative services separately offered or agreed. A “Project” is a VERALEX service record; the “Project Tracking Portal” displays selected project progress. A “Project Access Link” is a confidential, time-limited link for an initial claim. A “Government Authority” is a public body responsible for an applicable official process or decision.']},
    {id:'website',title:'Website information',paragraphs:['Service descriptions, articles, and general guidance are informational. They are not necessarily advice tailored to your circumstances, a definitive statement of current regulation, or a promise that a particular application will be approved. Ask VERALEX to assess your specific matter.']},
    {id:'engagement',title:'Consultation and engagement',paragraphs:['An initial inquiry or consultation does not by itself establish a paid engagement. VERALEX and the client agree the scope, applicable fees, and deliverables separately. An administrator creates a tracking project after the relevant operational arrangements; a project record alone does not change an agreed service scope.']},
    {id:'responsibilities',title:'Client responsibilities',paragraphs:['Provide accurate and reasonably current information, respond to reasonable service requests, and provide required information through channels agreed with the VERALEX team. Protect account access and confidential project links, do not forward an unclaimed link to an unauthorized person, and promptly report suspected misuse or incorrect access.']},
    {id:'google',title:'Google account access',paragraphs:['Where supported, clients sign in with Google. Safeguard your Google account and review Google’s applicable terms. Signing in proves control of that account for the portal flow; it does not independently establish your real-world identity. VERALEX does not ask for your Google password.']},
    {id:'links',title:'Claiming a project access link',paragraphs:['After a project is created, VERALEX may send a confidential access link, including through WhatsApp. The first eligible Google-authenticated account to successfully use a valid unclaimed link may claim the project. Keep the link private. If the wrong account claims it or it is exposed, contact VERALEX promptly. VERALEX may revoke access or issue a replacement after appropriate operational checks. A project ID alone does not grant access.']},
    {id:'tracking',title:'Project tracking information',paragraphs:['The portal offers visibility into progress recorded by VERALEX personnel. Updates may not appear immediately and are not a live feed from any Government Authority. Stages may depend on third parties and official review. A displayed milestone, estimate, or completed internal task does not guarantee an official decision or approval. The portal is not an Indonesian government website.']},
    {id:'government',title:'Government procedures and outcomes',paragraphs:['Requirements, official charges, and processing times may change. Relevant Government Authorities retain decision-making power. VERALEX cannot guarantee approval or a fixed official completion date unless a specific commitment is expressly and lawfully agreed in writing. Operational workflow descriptions may be adapted to the actual case and current rules.']},
    {id:'fees',title:'Fees and payment',paragraphs:['A quotation or service agreement identifies the applicable VERALEX fee, deliverables, and payment arrangements. Official government charges and third-party costs may be separate where stated. Any additional service or charge should be agreed before it is incurred. A transaction is confirmed according to the applicable verified payment process; this page does not create a new payment schedule or price.']},
    {id:'priority',title:'Priority handling',paragraphs:['If offered and eligible, “VERALEX Priority Handling” relates to selected internal VERALEX work only. It cannot speed up or influence an official decision. Availability, conditions, and price require confirmation. Activation of a paid option depends on an actual verified transaction; the tracking portal currently has no configured priority payment gateway.']},
    {id:'cancellation',title:'Cancellation and refunds',paragraphs:['The applicable cancellation or refund terms must be set out in the agreed quotation, service agreement, or separately approved policy and remain subject to applicable consumer law. If no separate cancellation or refund term applies to a particular case, contact VERALEX to discuss the circumstances. This page does not establish a blanket non-refundable rule, penalty, deduction, or refund deadline.']},
    {id:'ip',title:'Intellectual property',paragraphs:['VERALEX branding, original site content, and materials remain with their respective rights holders and may be used only for ordinary access to the site or as otherwise authorized. This does not transfer ownership of client intellectual property or third-party marks to VERALEX. Do not reproduce or represent VERALEX materials as your own without permission.']},
    {id:'acceptable',title:'Acceptable use',paragraphs:['Do not attempt to access another client’s project, misuse credentials or links, interfere with service availability, use harmful automation, or use the site for unlawful purposes. Security testing or bulk access requires prior authorization. These restrictions apply proportionately to protect users and operations.']},
    {id:'restrictions',title:'Account and access restrictions',paragraphs:['VERALEX may restrict, revoke, or restore access when reasonably needed for security, a compromised link, incorrect claim, suspected misuse, or legitimate service operations. Requests concerning access should be assessed in context and in accordance with applicable law and any separate agreement.']},
    {id:'availability',title:'Service availability',paragraphs:['The website and portal may be temporarily unavailable because of maintenance, network failures, security work, or third-party services. VERALEX should take reasonable steps to address issues but does not promise uninterrupted access or instantaneous updates.']},
    {id:'liability',title:'Responsibility and legal limits',paragraphs:['Rights and responsibilities are governed by applicable law and any agreed service contract. Nothing here excludes mandatory consumer or data protection rights, or liability that cannot lawfully be excluded, including for misconduct or negligence where applicable. General website information should not replace an assessment of a specific legal or regulatory matter.']},
    {id:'privacy',title:'Privacy',paragraphs:['Personal data handling is explained in the Privacy Policy. Review it for information on Google sign-in, confidential project links, external communication channels, service providers, and your applicable rights.']},
    {id:'changes',title:'Changes to these terms',paragraphs:['VERALEX may update these terms as its services or applicable law change. Material changes should be communicated through appropriate channels. Continued website use alone is not assumed to establish valid consent where a separate agreement or consent is legally necessary.']},
    {id:'law',title:'Applicable law and disputes',paragraphs:['Indonesian law applies to these website terms, subject to mandatory rules and the circumstances of a particular engagement. Parties should first contact each other to discuss a concern. Any agreed dispute process in a separate service contract remains relevant. These website terms do not establish an exclusive court or mandatory arbitration forum.']},
    {id:'contact',title:'Contact',paragraphs:['Contact VERALEX at admin@veralexconsulting.com or WhatsApp +62 812 1947 6385. Service-specific questions, including cancellation or refunds, can be discussed through these channels. Do not send identity documents through the project tracking portal.']},
  ],
};

const id: LegalDocument = {
  title:'Syarat & Ketentuan',description:'Ketentuan penggunaan situs dan portal pelacakan proyek klien VERALEX CONSULTING.',intro:'Ketentuan ini menjelaskan penggunaan situs dan portal klien VERALEX. Penawaran atau perjanjian layanan yang disepakati secara khusus menetapkan ruang lingkup, harga, dan hasil layanan.',sections:[
    {id:'scope',title:'Ruang lingkup dan perjanjian',paragraphs:['Ketentuan ini mencakup situs publik, akun, portal pelacakan proyek, dan fitur digital terkait dengan nama VERALEX CONSULTING. Ketentuan ini tidak secara diam-diam menggantikan penawaran tertulis atau perjanjian layanan tersendiri. Jika perjanjian khusus mengatur suatu hal layanan secara berbeda, perjanjian itu berlaku untuk hal tersebut sepanjang diizinkan hukum.']},
    {id:'definitions',title:'Definisi',paragraphs:['“VERALEX” berarti pengelola situs dan layanan VERALEX CONSULTING. “Pengguna” adalah pengunjung atau pemakai situs; “Klien” adalah pihak yang menggunakan layanan atau mendapat akses proyek; “Administrator” adalah anggota tim VERALEX yang berwenang. “Layanan” adalah jasa konsultasi dan administrasi yang ditawarkan atau disepakati secara terpisah. “Proyek” adalah catatan layanan VERALEX; “Portal Pelacakan Proyek” menampilkan sebagian progres. “Tautan Akses Proyek” adalah tautan rahasia dengan masa berlaku terbatas untuk klaim pertama. “Instansi Pemerintah” adalah badan publik yang menangani proses atau keputusan resmi terkait.']},
    {id:'website',title:'Informasi di situs',paragraphs:['Deskripsi layanan, artikel, dan panduan umum bersifat informatif. Isinya tidak selalu merupakan nasihat yang disesuaikan dengan keadaan Anda, uraian pasti atas aturan terbaru, atau janji bahwa suatu permohonan akan disetujui. Mintalah penilaian VERALEX untuk persoalan khusus Anda.']},
    {id:'engagement',title:'Konsultasi dan penggunaan layanan',paragraphs:['Pertanyaan atau konsultasi awal tidak otomatis membentuk hubungan layanan berbayar. VERALEX dan klien menyepakati ruang lingkup, biaya, serta hasil layanan secara terpisah. Administrator membuat proyek pelacakan setelah pengaturan operasional terkait; catatan proyek saja tidak mengubah ruang lingkup yang telah disepakati.']},
    {id:'responsibilities',title:'Tanggung jawab klien',paragraphs:['Berikan informasi yang akurat dan cukup mutakhir, tanggapi permintaan layanan yang wajar, dan kirim informasi yang dibutuhkan melalui kanal yang disepakati dengan tim VERALEX. Lindungi akses akun dan tautan proyek yang bersifat rahasia, jangan teruskan tautan yang belum diklaim kepada pihak tanpa wewenang, serta segera laporkan dugaan penyalahgunaan atau akses yang keliru.']},
    {id:'google',title:'Akses akun Google',paragraphs:['Jika didukung, klien masuk dengan Google. Lindungi akun Google Anda dan perhatikan ketentuan Google yang berlaku. Login membuktikan penguasaan akun tersebut untuk alur portal, tetapi tidak dengan sendirinya membuktikan identitas Anda di dunia nyata. VERALEX tidak meminta kata sandi Google Anda.']},
    {id:'links',title:'Klaim tautan akses proyek',paragraphs:['Setelah proyek dibuat, VERALEX dapat mengirim tautan akses rahasia, termasuk melalui WhatsApp. Akun Google pertama yang memenuhi syarat dan berhasil memakai tautan sah yang belum diklaim dapat mengklaim proyek. Jaga kerahasiaannya. Jika akun yang salah mengklaim atau tautan tersebar, segera hubungi VERALEX. VERALEX dapat mencabut akses atau menerbitkan pengganti setelah pemeriksaan operasional yang sesuai. ID proyek saja tidak memberikan akses.']},
    {id:'tracking',title:'Informasi pelacakan proyek',paragraphs:['Portal menampilkan progres yang dicatat oleh personel VERALEX. Pembaruan dapat tidak langsung tampil dan bukan data langsung dari Instansi Pemerintah. Sebagian tahapan bergantung pada pihak ketiga dan pemeriksaan resmi. Tahap yang ditampilkan, perkiraan, atau tugas internal yang selesai bukan jaminan keputusan atau persetujuan resmi. Portal ini bukan situs pemerintah Indonesia.']},
    {id:'government',title:'Prosedur dan keputusan pemerintah',paragraphs:['Persyaratan, biaya resmi, dan waktu pemrosesan dapat berubah. Instansi Pemerintah terkait tetap berwenang mengambil keputusan. VERALEX tidak dapat menjamin persetujuan atau tanggal penyelesaian resmi yang tetap, kecuali komitmen tertentu disepakati secara tegas dan sah secara tertulis. Uraian alur kerja operasional dapat disesuaikan dengan kasus dan aturan yang berlaku.']},
    {id:'fees',title:'Biaya dan pembayaran',paragraphs:['Penawaran atau perjanjian layanan menetapkan biaya VERALEX, hasil layanan, dan pengaturan pembayaran. Biaya resmi pemerintah dan biaya pihak ketiga dapat terpisah jika dinyatakan demikian. Layanan atau biaya tambahan sebaiknya disepakati sebelum timbul. Transaksi dikonfirmasi menurut proses pembayaran yang benar-benar berlaku; halaman ini tidak menetapkan jadwal atau harga baru.']},
    {id:'priority',title:'Penanganan prioritas',paragraphs:['Jika ditawarkan dan memenuhi syarat, “Layanan Prioritas Penanganan VERALEX” hanya terkait pekerjaan internal VERALEX tertentu. Layanan ini tidak dapat mempercepat atau memengaruhi keputusan resmi. Ketersediaan, syarat, dan harga perlu dikonfirmasi. Aktivasi opsi berbayar bergantung pada transaksi yang benar-benar terverifikasi; portal pelacakan saat ini belum memiliki gerbang pembayaran prioritas yang dikonfigurasi.']},
    {id:'cancellation',title:'Pembatalan dan pengembalian dana',paragraphs:['Syarat pembatalan atau pengembalian dana yang berlaku harus ditetapkan dalam penawaran, perjanjian layanan, atau kebijakan terpisah yang telah disetujui dan tetap tunduk pada hukum perlindungan konsumen. Jika suatu kasus tidak diatur dalam ketentuan pembatalan atau pengembalian dana tersendiri, hubungi VERALEX untuk membahas keadaannya. Halaman ini tidak menetapkan larangan pengembalian dana secara menyeluruh, penalti, potongan, atau tenggat pengembalian dana.']},
    {id:'ip',title:'Kekayaan intelektual',paragraphs:['Merek VERALEX, konten asli situs, dan materi tetap menjadi hak pemegangnya masing-masing dan hanya boleh digunakan untuk mengakses situs sebagaimana mestinya atau sesuai izin lain. Hal ini tidak mengalihkan hak kekayaan intelektual klien atau merek pihak ketiga kepada VERALEX. Jangan menggandakan atau mengaku sebagai pemilik materi VERALEX tanpa izin.']},
    {id:'acceptable',title:'Penggunaan yang diperbolehkan',paragraphs:['Jangan mencoba mengakses proyek klien lain, menyalahgunakan kredensial atau tautan, mengganggu ketersediaan layanan, memakai otomasi berbahaya, atau menggunakan situs untuk tujuan melanggar hukum. Pengujian keamanan atau akses massal memerlukan izin terlebih dahulu. Pembatasan ini diterapkan secara proporsional untuk melindungi pengguna dan operasi.']},
    {id:'restrictions',title:'Pembatasan akun dan akses',paragraphs:['VERALEX dapat membatasi, mencabut, atau memulihkan akses jika secara wajar diperlukan untuk keamanan, tautan yang bocor, klaim yang keliru, dugaan penyalahgunaan, atau kebutuhan operasional layanan yang sah. Permintaan terkait akses dinilai sesuai konteks, hukum yang berlaku, dan perjanjian terpisah jika ada.']},
    {id:'availability',title:'Ketersediaan layanan',paragraphs:['Situs dan portal dapat sementara tidak tersedia karena pemeliharaan, gangguan jaringan, penanganan keamanan, atau layanan pihak ketiga. VERALEX sepatutnya mengambil langkah wajar untuk menangani masalah, tetapi tidak menjanjikan akses tanpa gangguan atau pembaruan seketika.']},
    {id:'liability',title:'Tanggung jawab dan batas hukum',paragraphs:['Hak dan tanggung jawab diatur oleh hukum yang berlaku serta perjanjian layanan terkait. Tidak ada ketentuan di sini yang menghapus hak wajib konsumen atau perlindungan data, atau tanggung jawab yang menurut hukum tidak dapat dikecualikan, termasuk atas kesalahan atau kelalaian jika berlaku. Informasi umum situs tidak menggantikan penilaian atas masalah hukum atau regulasi tertentu.']},
    {id:'privacy',title:'Privasi',paragraphs:['Pengelolaan data pribadi dijelaskan dalam Kebijakan Privasi. Bacalah untuk mengetahui informasi mengenai login Google, tautan proyek rahasia, kanal komunikasi eksternal, penyedia layanan, dan hak Anda yang berlaku.']},
    {id:'changes',title:'Perubahan ketentuan',paragraphs:['VERALEX dapat memperbarui ketentuan ini seiring perubahan layanan atau hukum. Perubahan penting sebaiknya disampaikan melalui kanal yang sesuai. Penggunaan situs yang berlanjut saja tidak dianggap otomatis sebagai persetujuan yang sah jika secara hukum diperlukan perjanjian atau persetujuan tersendiri.']},
    {id:'law',title:'Hukum yang berlaku dan sengketa',paragraphs:['Hukum Indonesia berlaku untuk ketentuan situs ini, dengan memperhatikan aturan wajib dan keadaan tiap hubungan layanan. Para pihak sebaiknya terlebih dahulu saling menghubungi untuk membahas persoalan. Mekanisme sengketa yang disepakati dalam kontrak layanan tersendiri tetap relevan. Ketentuan situs ini tidak menetapkan pengadilan eksklusif atau arbitrase wajib.']},
    {id:'contact',title:'Kontak',paragraphs:['Hubungi VERALEX melalui admin@veralexconsulting.com atau WhatsApp +62 812 1947 6385. Pertanyaan mengenai layanan tertentu, termasuk pembatalan atau pengembalian dana, dapat dibahas melalui kanal tersebut. Jangan mengirim dokumen identitas melalui portal pelacakan proyek.']},
  ]
};

const zh: LegalDocument = {
  title:'条款与条件',description:'VERALEX CONSULTING 网站及客户项目进度门户的使用条款。',intro:'本条款说明 VERALEX 网站及客户门户的使用方式。具体服务范围、费用及交付内容，以双方另行确认的报价或服务协议为准。',sections:[
    {id:'scope',title:'适用范围与协议',paragraphs:['本条款适用于以 VERALEX CONSULTING 名义提供的公开网站、账户、项目进度门户及相关数字功能，不会默默取代另行达成的书面报价或服务协议。若单独协议对某项具体服务另有约定，在法律允许范围内，以该协议对该事项的规定为准。']},
    {id:'definitions',title:'定义',paragraphs:['“VERALEX”指 VERALEX CONSULTING 网站及服务的运营方。“用户”指访问或使用网站的人；“客户”指使用服务或获得项目权限的人；“管理员”指获授权的 VERALEX 团队成员。“服务”指另行提供或约定的咨询及行政协助；“项目”指 VERALEX 的服务记录；“项目进度门户”显示部分进度。“项目访问链接”是用于首次认领、具有期限且须保密的链接；“政府机关”指负责相关官方流程或决定的公共机构。']},
    {id:'website',title:'网站信息',paragraphs:['服务介绍、文章及一般指南仅供参考，未必构成针对您具体情况的意见、现行法规的最终说明，也不保证申请获批。具体事项请联系 VERALEX 评估。']},
    {id:'engagement',title:'咨询与服务委托',paragraphs:['初步咨询或询问本身不会自动成立付费委托。具体服务范围、费用和交付成果由 VERALEX 与客户另行约定。管理员在完成相关业务安排后创建进度项目；项目记录本身不改变既定服务范围。']},
    {id:'responsibilities',title:'客户责任',paragraphs:['请提供准确且适当更新的信息，回应合理的服务请求，并通过与 VERALEX 团队约定的渠道提供所需资料。请保护账户及保密项目链接，勿将未认领链接转发给未经授权者；如怀疑滥用或权限有误，请及时报告。']},
    {id:'google',title:'Google 账户访问',paragraphs:['在支持的情况下，客户通过 Google 登录。请妥善保护 Google 账户，并查阅其适用条款。登录仅证明该账户在门户流程中受到控制，并不单独证明现实身份。VERALEX 不会索取您的 Google 密码。']},
    {id:'links',title:'认领项目访问链接',paragraphs:['项目创建后，VERALEX 可通过 WhatsApp 等渠道发送保密访问链接。首个使用有效且未被认领链接、符合条件的 Google 登录账户可认领项目。请勿向未经授权者转发。如链接泄露或被错误账户认领，请立即联系 VERALEX。经适当业务核查后，VERALEX 可撤销权限或签发新链接。仅知道项目 ID 不代表获得访问权限。']},
    {id:'tracking',title:'项目进度信息',paragraphs:['门户显示由 VERALEX 人员维护的进度，更新可能不会即时出现，也并非政府机关的实时数据。部分阶段取决于第三方和官方审查。显示的里程碑、预计时间或已完成内部任务均不保证官方决定或批准。本门户并非印度尼西亚政府网站。']},
    {id:'government',title:'政府程序与结果',paragraphs:['要求、官方收费及办理时间可能变化。相关政府机关保留决定权。除非在法律允许范围内以书面明确约定具体承诺，VERALEX 不保证获批或固定的官方完成日期。操作流程说明可能依个案及现行规则调整。']},
    {id:'fees',title:'费用与付款',paragraphs:['报价或服务协议载明 VERALEX 服务费、交付内容及付款安排。若有说明，政府收费和第三方费用可能另计。新增服务或费用应在发生前协商。交易按实际适用的付款核实流程确认；本页面不设定新的付款时间表或价格。']},
    {id:'priority',title:'优先处理',paragraphs:['若提供且符合条件，“VERALEX 优先处理服务”仅适用于指定的 VERALEX 内部工作，无法加快或影响官方决定。服务是否提供、条件和价格均须确认。付费选项的启用取决于真实且已核实的交易；当前进度门户尚未配置优先服务支付网关。']},
    {id:'cancellation',title:'取消与退款',paragraphs:['适用的取消或退款规定应载于已确认的报价、服务协议或另行批准的政策，并遵守适用的消费者保护法律。如具体情况不受单独取消或退款条款约束，请联系 VERALEX 讨论。本页面不设定一概不退款、取消罚金、扣费或退款期限。']},
    {id:'ip',title:'知识产权',paragraphs:['VERALEX 品牌、网站原创内容和资料归各自权利人所有，仅可用于正常访问网站或经授权的用途。本条款不将客户知识产权或第三方商标转让给 VERALEX。未经许可，不得复制 VERALEX 资料或将其冒称为自己的资料。']},
    {id:'acceptable',title:'合理使用',paragraphs:['不得试图访问其他客户的项目、滥用凭据或链接、干扰服务、使用有害自动化程序，或将网站用于违法目的。安全测试或批量访问须事先取得许可。相关限制应适度适用，以保护用户和运营。']},
    {id:'restrictions',title:'账户及权限限制',paragraphs:['如因安全、链接泄露、认领错误、疑似滥用或正当运营需要，VERALEX 可在合理必要范围内限制、撤销或恢复访问。权限请求应结合具体情况、适用法律及单独协议进行评估。']},
    {id:'availability',title:'服务可用性',paragraphs:['网站和门户可能因维护、网络故障、安全处理或第三方服务而暂时无法使用。VERALEX 应采取合理措施解决问题，但不承诺服务永不中断或更新即时显示。']},
    {id:'liability',title:'责任与法律限制',paragraphs:['双方权利义务受适用法律及相关服务协议约束。本条款不排除依法必须保障的消费者或数据保护权利，也不免除法律禁止排除的责任，包括在适用情况下因不当行为或过失产生的责任。网站一般信息不能代替对具体法律或监管事项的评估。']},
    {id:'privacy',title:'隐私',paragraphs:['个人数据处理另见《隐私政策》，其中说明 Google 登录、保密项目链接、外部沟通渠道、服务提供商以及适用的个人权利。']},
    {id:'changes',title:'条款变更',paragraphs:['VERALEX 可因服务或适用法律变化更新本条款。重大变更应通过适当渠道通知。若法律要求单独协议或同意，不能仅凭继续使用网站推定已取得有效同意。']},
    {id:'law',title:'适用法律与争议',paragraphs:['本网站条款适用印度尼西亚法律，同时须考虑强制性规则及具体服务关系。发生问题时，双方宜先相互联系沟通。单独服务合同中约定的争议解决机制仍有相关性。本网站条款不设定专属法院或强制仲裁。']},
    {id:'contact',title:'联系方式',paragraphs:['您可通过 admin@veralexconsulting.com 或 WhatsApp +62 812 1947 6385 联系 VERALEX。有关具体服务、取消或退款的问题也可通过这些渠道咨询。请勿通过项目进度门户发送身份证件。']},
  ]
};

export const termsDocuments: Record<Lang, LegalDocument> = {en,id,zh};
